defaults: &defaults
  # Credentials for connecting to a Fedora 3 backend:
  fedora3_host: http://myserver:8088
  fedora3_api: http://myserver:8088/fedora
  fedora3_username: username
  fedora3_password: password
  fedora3_pid_namespace: vudl

  solr_query_url: http://myserver:8983/solr/core/query

  # Settings for Tesseract OCR
  tesseract_path: /usr/local/bin/tesseract

  # Settings for ocrmypdf (omit setting to skip this step if you aren't using it)
  #ocrmypdf_path: /usr/local/bin/ocrmypdf

  # VuFind Base URL
  vufind_url: https://myserver

  # Temp directory used for PDF generation
  pdf_directory: /tmp/

  # Settings for FFmpeg
  #ffmpeg_path: /usr/bin/ffmpeg

  # Settings for the textcleaner OCR preparation script. It can be downloaded
  # from http://www.fmwconcepts.com/imagemagick/textcleaner/index.php
  textcleaner_path: /usr/local/bin/textcleaner
  textcleaner_switches: -g -e stretch -u -T

  # Base path where incoming files are stored; this must contain two levels
  # of subdirectories, the first representing categories and the second
  # representing jobs within those categories.
  holding_area_path: /usr/local/holding

  # Base path where processed files are moved after ingestion.
  processed_area_path: /usr/local/processed

  # Should we require a login? (Set to false for easy debugging; DO NOT DISABLE
  # IN PRODUCTION)
  require_login: true

  # An array of uids that are allowed to log in (e.g. [user1, user2, user3]; set
  # to "*" to allow all users). See also config/initializers/omniauth.rb for
  # authentication settings.
  user_whitelist: "*"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
