name: Lint Pull Requests

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Lint
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install
          npm run install-all

      - name: Run prettier
        run: npm run format
        with:
          working-directory: $GITHUB_WORKSPACE

      - name: Auto-commit fixes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: "['api/*.js', 'api/src/', 'client/src/']"

      - name: Run eslint
        run: npm run lint
