name: Lint Pull Requests

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Lint
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Install api and client dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install
          working-directory: |
            api
            client

      - name: Run eslint
        run: npm run lint
