name: Lint Pull Requests

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Lint
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install
          cd client && npm install
          cd api && npm install

      - name: Run eslint
        run: npm run lint
