name: Lint Pull Requests

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: |
          npm install
          npm run setup

      - name: Run prettier
        run: npm run format

      - name: Auto-commit fixes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "['api/*.js', 'api/src/', 'client/src/']"

      - name: Run eslint
        run: npm run lint

      - name: Run API tests
        run: npm run api:test

      - name: Run client tests
        run: npm run client:test
