# This is a basic workflow to help you get started with Actions

name: Lint Pull Requests

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events
  pull_request:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: |
          npm install
          cd client && npm install
          cd api && npm install          

      - name: Lint
        run: npm run lint -- --fix
