# This is a basic workflow to help you get started with Actions

name: Lint Pull Requests

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the dev branch
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Node
        with:
          node-version: 'latest'

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: |
          npm install
          cd client && npm install
          cd api && npm install          

      # Runs a set of commands using the runners shell
      - name: Lint
        run: npm run lint -- --fix
